config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root "customers#index"
  get "alphabetized", to: "customers#alphabetized"
  get "missing_email", to: "customers#missing_email"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @cust = Customer.find(params[:id])
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where("email == ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="tile is-parent">
  <div class="card p-4">
    <p class="title is-5"><%= customer.full_name %></p>
    <div class="card-image px-4">
      <figure class="image is-24by3">
        <%= image_tag customer.image %>
      </figure>
    </div>
    <div class="card-content">
      <div class="content">
        <p><%= customer.phone_num %></p>
        <p><%= customer.email %></p>
        <p><%= customer.notes %></p>
      </div>
    </div>
  </div>
</div>

app/views/customers/_customerView.html.erb
<h1 class="title">Customers</h1>
<section class="section">
  <div class="tile is-ancestor">
    <%= render partial: "customers/customer", collection: @customers %>
  </div>
</section>

app/views/customers/alphabetized.html.erb
<%= render "layouts/navbar" %>
<%= render partial: "customers/customerView" %>

app/views/customers/index.html.erb
<h1 class="Title">Customers</h1>
<section class="section">
  <div class="columns is-multiline">
    <%= render partial: "customers/customer", collection: @customers, locals: { show_link: true } %>
  </div>
</section>

app/views/customers/missing_email.html.erb
<%= render "layouts/navbar" %>
<%= render partial: "customers/customerView" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to "Customers", root_path %>
      </div>
      <div class="navbar-item">
        <%= link_to "Customers - A - Z", alphabetized_path %>
      </div>
      <div class="navbar-item">
        <%= link_to "Customers - Missing email", missing_email_path %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>